ktor:
  application:
    modules:
      - com.wave.ApplicationKt.module
  deployment:
    port: 9999
storage:
  driverClassName: "com.impossibl.postgres.jdbc.PGDriver"
  jdbcURL: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}